Fix branch issue

diff --git a/.github/workflows/gki-kernel.yml b/.github/workflows/gki-kernel.yml
--- a/.github/workflows/gki-kernel.yml
+++ b/.github/workflows/gki-kernel.yml
@@ -201,21 +201,23 @@ jobs:
           
           case "$branch_input" in
             "Stable")
-              if [ "${{ inputs.kernelsu_variant }}" == "WKSU" ]; then
-                echo "BRANCH=-s stable" >> $GITHUB_ENV
-
-              else
-                echo "BRANCH=-s builtin" >> $GITHUB_ENV
-              fi
+              case "$variant_input" in
+                "Official" | "MKSU") echo "BRANCH=-s main" >> $GITHUB_ENV ;;
+                "Next" | "WKSU)      echo "BRANCH=-s stable" >> $GITHUB_ENV ;;
+                "SukiSU")           echo "BRANCH=-s main" >> $GITHUB_ENV ;;
+                *) 
+                  echo "Invalid choice '$variant_input'" >&2
+                  exit 1
+                  ;;
+              esac
               ;;
             "Dev")
               case "$variant_input" in
-                "Official" | "MKSU") echo "BRANCH=-s main" >> $GITHUB_ENV ;;
-                "Next")              echo "BRANCH=-s next-susfs-dev" >> $GITHUB_ENV ;;
-                "SukiSU")           echo "BRANCH=-s v4.1.0" >> $GITHUB_ENV ;;
-                "WKSU")             echo "BRANCH=-s canary" >> $GITHUB_ENV ;;
+                "Official" | "MKSU" | "Next") echo "BRANCH=-s dev" >> $GITHUB_ENV ;;
+                "SukiSU")                     echo "BRANCH=-s builtin" >> $GITHUB_ENV ;;
+                "WKSU")                       echo "BRANCH=-s canary" >> $GITHUB_ENV ;;
                 *) 
-                  echo "错误：未定义开发分支的变体 '$variant_input'" >&2
+                  echo "Invalid choice '$variant_input'" >&2
                   exit 1
                   ;;
               esac
