Remove chinese stuff ig

diff --git a/.github/workflows/gki-kernel.yml b/.github/workflows/gki-kernel.yml
--- a/.github/workflows/gki-kernel.yml
+++ b/.github/workflows/gki-kernel.yml
@@ -196,7 +196,7 @@ jobs:
           variant_input="${{ inputs.kernelsu_variant }}"
           
           case "$branch_input" in
-            "Stable(标准)")
+            "Stable")
               if [ "${{ inputs.kernelsu_variant }}" == "WKSU" ]; then
                 echo "BRANCH=-s stable" >> $GITHUB_ENV
 
@@ -204,7 +204,7 @@ jobs:
                 echo "BRANCH=-s builtin" >> $GITHUB_ENV
               fi
               ;;
-            "Dev(开发)")
+            "Dev")
               case "$variant_input" in
                 "Official" | "MKSU") echo "BRANCH=-s main" >> $GITHUB_ENV ;;
                 "Next")              echo "BRANCH=-s next-susfs-dev" >> $GITHUB_ENV ;;
@@ -217,7 +217,7 @@ jobs:
               esac
               ;;
             *)
-              echo "错误：需要自定义分支时未提供参数" >&2
+              echo "Invalid choice! Aborting" >&2
               exit 1
               ;;
           esac
